BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Users] ALTER COLUMN [Cpf] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Users] ALTER COLUMN [Nome] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Users] ADD [Iduserasaas] NVARCHAR(1000) CONSTRAINT [Users_Iduserasaas_df] DEFAULT 'null';

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
