BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Users] ADD [Cpf] NVARCHAR(1000) NOT NULL CONSTRAINT [Users_Cpf_df] DEFAULT 'null',
[Nome] NVARCHAR(1000) NOT NULL CONSTRAINT [Users_Nome_df] DEFAULT 'null';

-- CreateTable
CREATE TABLE [dbo].[Group] (
    [ID] INT NOT NULL IDENTITY(1,1),
    [Groupid] NVARCHAR(1000) NOT NULL,
    [Size] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [Group_pkey] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [Group_ID_key] UNIQUE NONCLUSTERED ([ID]),
    CONSTRAINT [Group_Groupid_key] UNIQUE NONCLUSTERED ([Groupid])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
